main.py
from flask import Flask

from routes.home import home_route
from routes.login import login_route

app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(login_route, prefix='login')

if __name__ == '__main__':
    app.run(debug=True)

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

@home_route.route('/header')
def header():
    return render_template('header.html')

@home_route.route('/feed')
def feed():
    return render_template('feed-store.html')

@home_route.route('/footer')
def footer():
    return render_template('footer.html')

routes/login.py
from flask import Blueprint, render_template

login_route = Blueprint('login', __name__)

@login_route.route('/')
def login_page():
    return render_template('login.html')

templates/feed-store.html
{% for i in range(4) %}
    <section>
        {% for i in range(5) %}
            <article>
                <figure class="item-img"></figure>
                <h4>Produto</h4>
                <h6>valor</h6>
            </article>
        {% endfor %}
    </section>
{% endfor %}

templates/header.html
<img src="{{ url_for('static', filename='imgs/gaiadelas-store-white.png') }}" id="logo">
<section>
    <nav>
        <a class="selected" href="{{ url_for('home.home') }}">Home</a>
        <a href="#">Categorias</a>
        <a href="#">Contato</a>
    </nav>
    <div class="user-img-container">
        <img src="{{ url_for('static', filename='imgs/user.png') }}" id="user">
    </div>
</section>

templates/index.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gaiadelas Store</title>
    <link rel="icon" href="{{ url_for('static', filename='imgs/icon.png') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/header.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/feed-store.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/footer.css') }}">
</head>

<body>
    <header id="main-header"></header>
    <main id="main-feed"></main>
    <footer id="main-footer"></footer>
</body>
<script src="{{ url_for('static', filename='js/script.js') }}"></script>
<script>
    render_container('/header', 'main-header')
    render_container('/feed', 'main-feed')
    render_container('/footer', 'main-footer')
</script>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gaiadelas - Vendas</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>

<body>
</body>

</html>